--
-- PostgreSQL database dump
--

-- Dumped from database version 10.6
-- Dumped by pg_dump version 10.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.userstb DROP CONSTRAINT user_pkey;
ALTER TABLE ONLY public.empresa DROP CONSTRAINT empresa_pkey;
DROP TABLE public.userstb;
DROP TABLE public.empresa;
DROP EXTENSION plpgsql;
DROP SCHEMA public;
--
-- Name: public; Type: SCHEMA; Schema: -; Owner: dbuser
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO dbuser;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: dbuser
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: empresa; Type: TABLE; Schema: public; Owner: dbuser
--

CREATE TABLE public.empresa (
    id integer NOT NULL,
    nome character varying(40) NOT NULL,
    rua character varying(40) NOT NULL,
    cidade character varying(40) NOT NULL,
    pais character varying(40) NOT NULL,
    longitude character varying(40) NOT NULL,
    latitude character varying(40) NOT NULL
);


ALTER TABLE public.empresa OWNER TO dbuser;

--
-- Name: empresa_id_seq; Type: SEQUENCE; Schema: public; Owner: dbuser
--

ALTER TABLE public.empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: userstb; Type: TABLE; Schema: public; Owner: dbuser
--

CREATE TABLE public.userstb (
    id integer NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.userstb OWNER TO dbuser;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: dbuser
--

ALTER TABLE public.userstb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: empresa; Type: TABLE DATA; Schema: public; Owner: dbuser
--

COPY public.empresa (id, nome, rua, cidade, pais, longitude, latitude) FROM stdin;
2	Empresa 1	rua 1	Porto	Portugal	155	160
3	Empresa 1	rua 1	Porto	Portugal	155	160
4	Empresa 2	Rua 2	Braga	Portugal	170	175
5	Empresa					
\.


--
-- Data for Name: userstb; Type: TABLE DATA; Schema: public; Owner: dbuser
--

COPY public.userstb (id, username, password) FROM stdin;
0	admin	admin
\.


--
-- Name: empresa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbuser
--

SELECT pg_catalog.setval('public.empresa_id_seq', 5, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbuser
--

SELECT pg_catalog.setval('public.user_id_seq', 1, false);


--
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: dbuser
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);


--
-- Name: userstb user_pkey; Type: CONSTRAINT; Schema: public; Owner: dbuser
--

ALTER TABLE ONLY public.userstb
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: dbuser
--

GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

